export const GET_ALL_HEROES = 'GET_ALL_HEROES'
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS'
export const FETCH_DATA_ERROR = 'FETCH_DATA_ERROR'
export const FETCH_DATA_PENDING = 'FETCH_DATA_PENDING'

export const GET_HERO_BY_ID = 'GET_HERO_BY_ID'
export const FILTER_HERO_LIST = 'FILTER_HERO_LIST'